apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6 # Public image from Docker Hub
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-config
          mountPath: /usr/share/nginx/html/index.html  # Mounting the file correctly
      volumes:
      - name: html-config
        configMap:
          name: nginx-html-config
          items:
          - key: index.html  # Only mount the specific file from the ConfigMap
            path: index.html  # Mount it directly as a file

